defaults:
  - base

# subsampling relevant for only for the ML model
reduced_resolution: 2
reduced_resolution_t: 1

ic_gen:
  _target_: al4pde.tasks.ic_gen.ic_gen_jorek.ICGenJOREK
  pool_path: "/leonardo_work/FUAL8_UKAEA_ML/apolansk/al4pde/data/data/jorek/pool"


param_gen:
  _target_: al4pde.tasks.param_gen.PDEParamGenerator
  min_val: 0 
  max_val: 0   
  log_scale: false

sim:
  _target_: al4pde.tasks.sim.jorek.JOREKSim
  pool_path: "/leonardo_work/FUAL8_UKAEA_ML/apolansk/al4pde/data/data/jorek/pool"

data_gen:
  num_test_batches: 60
  num_initial_batches: 195 #Should be the same as the number of runs in initial 
  batch_size: 1