defaults:
  - base  

_target_: al4pde.prob_models.PRE_model.PREModel

# Remove ensemble-specific parameters (so they are not passed to PREModel)
num_models_ensemble: null
unc_roll_out_mode: null
synchronized_training: null
first_model_prediction: null

scheduler:
  _target_: pdearena.lr_scheduler.LinearWarmupCosineAnnealingLR
  __args__:
    - ${prob_model.model_wrapper.optimizer}  # Pass the optimizer as a positional argument
  warmup_epochs: 0
  warmup_start_lr: 1e-08
  eta_min: 1e-05
  max_epochs: '${num_epochs}'
  

